config/routes.rb
Rails.application.routes.draw do
  resources :users, except: [:index] do
    member do
      get 'articles'
      get 'comments'
    end
  end

  resources :articles do
    member do
      resources :comments, except: [:index, :show]
    end
  end

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'logout' => 'sessions#destroy'

  root 'articles#index'
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :author, class_name: "User"
  has_many :comments
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :commenter, class_name: "User"
  belongs_to :article
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :articles, foreign_key: :author_id
  has_many :comments, foreign_key: :commenter_id

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :find_article, only: [:show]
  before_action :check_logged_in, only: [:new, :create]

  def index
    @articles = Article.all
  end

  def show
    @comment = Comment.new
    # @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params.merge(author_id: session[:user_id]))
    if @article.save
      redirect_to articles_path
    else
      render 'new'
    end
  end

  private
  def find_article
    @article ||= Article.find_by(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :body, :author_id, :url)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end

  def create

    @comment = Comment.new(comment: params[:comment], commenter_id: 1, article_id: params[:id])
    if @comment.save
      redirect_to article_path
    else
      render article_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(username: params['/login'][:username])
    if user && user.authenticate(params['/login'][:password])
      session[:user_id] = user.id
      redirect_to user_path(user)
    else
      redirect_to '/login'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/login'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # before_action :check_logged_in, except: [:new]
  # before_action :find_user, except: [:new]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      render 'new'
    end
  end

  def show
  end

  def comments
  end

  private
  def find_user
    @user ||= User.find_by(params[:id])
  end

  def user_params
    params.require(:user).permit(:username, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    @current_user ||= User.find_by(id: session[:id])
  end

  def check_logged_in
    redirect_to '/users/new' unless logged_in?
  end

  def logged_in?
    current_user != nil
  end

  def check_owner(object)
    current_user == object
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
  def comment_link(article)
    link_to pluralize(article.comments.count, 'comment'), article_path(article)
  end
end

app/views/articles/_article.html.erb
<li><%= link_to article.title, article.url %>
  <ul>
    <li><%= article.author.username %></li>
    <li><%= comment_link(article) %></li>
    <li><%= time_ago_in_words(article.created_at) %> ago</li>
  </ul>
</li>

app/views/articles/_comment.html.erb
<li><%= link_to comment.commenter.username, user_path %> <%= time_ago_in_words(comment.created_at) %> ago</li>
<li><%= comment.comment %></li><br>

app/views/articles/_new_comment.html.erb
<%= form_for(@comment) do |f| %>

  <%= f.label :comment %>
  <%= f.text_area :comment %><br>

  <%= f.submit %>

<% end %>

app/views/articles/index.html.erb
<%= link_to 'New Article', new_article_path  %>
<ol>
  <%= render @articles %>
</ol>

app/views/articles/new.erb
<%= form_for @article do |f| %>

  <%= f.label :title %>
  <%= f.text_field :title %><br>

  <%= f.label :url %>
  <%= f.text_field :url %><br>

  <%= f.label :body %>
  <%= f.text_area :body %><br>

  <%= f.submit %>

<% end %>

app/views/articles/show.html.erb
<h1><%= link_to @article.title, @article.url %></h1>
<h4><%= comment_link(@article) %></h4>

<%= render 'new_comment' %>

<ul>
  <%= render partial: 'comment', collection: @article.comments, as: :comment %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HackerNewsClone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= link_to 'Home', root_path %>
  <%= link_to 'Register', new_user_path %>
  <%= link_to 'Login', login_path %>
  <%= link_to 'Logout', logout_path %>
<%= yield %>

</body>
</html>

app/views/users/articles.html.erb
articles.html.erb

app/views/users/comments.html.erb
comments.html.erb

app/views/users/new.html.erb
<%= form_for @user do |f| %>

  <%= f.label :username %>
  <%= f.text_field :username %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.submit %>

<% end %>

app/views/users/show.html.erb
show.html.erb